### ISSUE TITLE
Throws an error when a group has no members

### ISSUE THREAD

**Issue by arduano** [dohomi/storyblok-generate-ts#16]
Although technically this shouldn't be happening in the future of my project, currently I'm just prototyping and I stumbled on the error I included below.

I suggest using `never[]` instead of `()[]` for groups that have no items.

```
Type: bloks array but not whitelisted (will result in all elements): main_page_storyblok
Group has no members:  fa388a95-aec5-4dcf-9ab0-84576a4885a6
Group has no members:  9632ab38-80f6-480b-9b94-73a555ce8751
ERROR SyntaxError: '=>' expected. (9:14)
   7 | subsubtitle?: string
   8 | buttons?: any[]
>  9 | sections?: ()[]
     |              ^
  10 | _uid: string
  11 | component: "main_page"
  12 | [k: string]: any
    at Ve (/home/arduano/programming/temp/new-next-test/node_modules/prettier/parser-typescript.js:1:15607)
    at vz (/home/arduano/programming/temp/new-next-test/node_modules/prettier/parser-typescript.js:280:5919)
    at Object.yz [as parse] (/home/arduano/programming/temp/new-next-test/node_modules/prettier/parser-typescript.js:280:6242)
    at Object.parse (/home/arduano/programming/temp/new-next-test/node_modules/prettier/index.js:7334:23)
    at coreFormat (/home/arduano/programming/temp/new-next-test/node_modules/prettier/index.js:8645:18)
    at formatWithCursor2 (/home/arduano/programming/temp/new-next-test/node_modules/prettier/index.js:8837:18)
    at /home/arduano/programming/temp/new-next-test/node_modules/prettier/index.js:37229:12
    at format (/home/arduano/programming/temp/new-next-test/node_modules/prettier/index.js:37243:12)
    at format (/home/arduano/programming/temp/new-next-test/node_modules/json-schema-to-typescript/dist/src/formatter.js:20:34)
    at /home/arduano/programming/temp/new-next-test/node_modules/json-schema-to-typescript/dist/src/index.js:163:56 {
  loc: { start: { line: 9, column: 14 } },
  codeFrame: '\x1B[0m \x1B[90m  7 |\x1B[39m subsubtitle\x1B[33m?\x1B[39m\x1B[33m:\x1B[39m string\x1B[0m\n' +
    '\x1B[0m \x1B[90m  8 |\x1B[39m buttons\x1B[33m?\x1B[39m\x1B[33m:\x1B[39m any[]\x1B[0m\n' +
    '\x1B[0m\x1B[31m\x1B[1m>\x1B[22m\x1B[39m\x1B[90m  9 |\x1B[39m sections\x1B[33m?\x1B[39m\x1B[33m:\x1B[39m ()[]\x1B[0m\n' +
    '\x1B[0m \x1B[90m    |\x1B[39m              \x1B[31m\x1B[1m^\x1B[22m\x1B[39m\x1B[0m\n' +
    '\x1B[0m \x1B[90m 10 |\x1B[39m _uid\x1B[33m:\x1B[39m string\x1B[0m\n' +
    '\x1B[0m \x1B[90m 11 |\x1B[39m component\x1B[33m:\x1B[39m \x1B[32m"main_page"\x1B[39m\x1B[0m\n' +
    '\x1B[0m \x1B[90m 12 |\x1B[39m [k\x1B[33m:\x1B[39m string]\x1B[33m:\x1B[39m any\x1B[0m'
}```

**Comment by dohomi** [comment]
I'm happy to check a PR, I never stumbled across this issue yet.

**Comment by arduano** [comment]
Opened PR #17
